### ISSUE TITLE
[FR]: Forsøger konfigurationen igen: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by dennisnn87** [MTrab/clever#20]
Efter seneste opdatering af HA

**Comment by MTrab** [comment]
Ikke meget du giver at gå efter.

Logs?! OS type, versioner, installations metode?!

**Comment by dennisnn87** [comment]
Beklager. Integrationen har kørt glimrende indtil jeg opdaterede til 2023.2.3Loggen sigerDenne fejl stammer fra en brugerdefineret integration.Logger: custom_components.clever.coordinatorSource: custom_components/clever/coordinator.py:40 Integration: Clever (documentation, issues) First occurred: 20.32.02 (102 occurrences) Last logged: 22.47.33Unexpected error fetching 'Hovedgaden 42-56, 4330 Hvalsø, DK' data: 'NoneType' object has no attribute 'items'Traceback (most recent call last):  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh    self.data = await self._async_update_data()  File "/config/custom_components/clever/coordinator.py", line 40, in _async_update_data    self.clever = await self.hass.async_add_executor_job(  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run    result = self.fn(*self.args, **self.kwargs)  File "/usr/local/lib/python3.10/site-packages/pyHASSClever/__init__.py", line 24, in __init__    self.update()  File "/usr/local/lib/python3.10/site-packages/pyHASSClever/__init__.py", line 137, in update    self._location = CleverLocations(self._identifier)  File "/usr/local/lib/python3.10/site-packages/pyHASSClever/locations.py", line 22, in __init__    self._location = self._get_location()  File "/usr/local/lib/python3.10/site-packages/pyHASSClever/locations.py", line 74, in _get_location    self._uuid = self._get_location_uid_from_id(self._identifier)  File "/usr/local/lib/python3.10/site-packages/pyHASSClever/locations.py", line 102, in _get_location_uid_from_id    for dataset in self._locations.items():AttributeError: 'NoneType' object has no attribute 'items'
    	Sendt fra Outlook til iOS
    
  

 Fra: Malene Trab ***@***.***>Sendt: tirsdag, februar 14, 2023 9:47 PMTil: MTrab/clever ***@***.***>Cc: dennisnn87 ***@***.***>; Author ***@***.***>Emne: Re: [MTrab/clever] Forsøger konfigurationen igen: 'NoneType' object has no attribute 'items' (Issue #20) 

Ikke meget du giver at gå efter.

Logs?! OS type, versioner, installations metode?!

**Comment by ptrabolt** [comment]
Jeg får samme meddelelse, også efter opgradering til 2023.2.3

**Comment by MTrab** [comment]
Desværre har dette intet med HA versionen at gøre.

Clever har lukket for den bagdør til deres API som jeg havde fundet, derfor virker dette ikke længere.

**Comment by martinwinds** [comment]
Håber du finder en ny bagdør. Det var en super fed integrations. Dejlig nem måde at se om der var ledigt. Fremfor Clever egen app. Ros for din integrations. Mvh Martin

**Comment by fribse** [comment]
Pokkers! Ellers meget populær video på min YT kanal.

**Comment by MTrab** [comment]
Rettelse kommer, når jeg lige har tid til at kode det - har fundet en metode

**Comment by martinwinds** [comment]
Hej  MaleneDet lyder mega fedt. Tak for en super fed integration MvhMartin Med venlig hilsen Martin Windsmose
