### ISSUE TITLE
Error 500 when trying to configure

### ISSUE THREAD

**Issue by fribse** [MTrab/clever#25]
### Environment:

Home Assistant version: 2023.3.6

## Chargepoint

Never got to this...

## Describe the bug

When I try to configure the integration I get this message:
Konfigurationsflow kunne ikke indlæses: 500 Internal Server Error Server got itself in trouble

## Debug log

```plaintext

Logger: aiohttp.server
Source: custom_components/clever/config_flow.py:28
Integration: Clever (documentation, issues)
First occurred: 13.38.10 (1 occurrences)
Last logged: 13.38.10

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 234, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 831, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 859, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/clever/config_flow.py", line 104, in async_step_user
    data_scheme = await data_schema(self.hass)
  File "/config/custom_components/clever/config_flow.py", line 28, in data_schema
    for location in clever.all_locations["clever"].items():
TypeError: 'NoneType' object is not subscriptable

```

**Comment by MTrab** [comment]
May I please redirect your attention to the front page of this integration?!
It's currently broken and I haven't had the time to implement the fix.
